/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './multiple-date-picker.module';
import * as import2 from '@angular/common';
import * as import3 from '@angular/forms';
class MultipleDatePickerModuleInjector extends import0.ɵNgModuleInjector<import1.MultipleDatePickerModule> {
  _CommonModule_0:import2.CommonModule;
  _ɵba_1:import3.ɵba;
  _FormsModule_2:import3.FormsModule;
  _MultipleDatePickerModule_3:import1.MultipleDatePickerModule;
  __NgLocalization_4:import2.NgLocaleLocalization;
  __ɵi_5:import3.ɵi;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_4():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_4 == null)) { (this.__NgLocalization_4 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_4;
  }
  get _ɵi_5():import3.ɵi {
    if ((this.__ɵi_5 == null)) { (this.__ɵi_5 = new import3.ɵi()); }
    return this.__ɵi_5;
  }
  createInternal():import1.MultipleDatePickerModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ɵba_1 = new import3.ɵba();
    this._FormsModule_2 = new import3.FormsModule();
    this._MultipleDatePickerModule_3 = new import1.MultipleDatePickerModule();
    return this._MultipleDatePickerModule_3;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ɵba)) { return this._ɵba_1; }
    if ((token === import3.FormsModule)) { return this._FormsModule_2; }
    if ((token === import1.MultipleDatePickerModule)) { return this._MultipleDatePickerModule_3; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_4; }
    if ((token === import3.ɵi)) { return this._ɵi_5; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const MultipleDatePickerModuleNgFactory:import0.NgModuleFactory<import1.MultipleDatePickerModule> = new import0.NgModuleFactory<any>(MultipleDatePickerModuleInjector,import1.MultipleDatePickerModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvbWFzdHJvcGluZ3Vpbm8vV29ya3MvUkwyL3JsMi9tdWx0aXBsZS1kYXRlLXBpY2tlci1hMi9zcmMvbXVsdGlwbGUtZGF0ZS1waWNrZXIubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvbWFzdHJvcGluZ3Vpbm8vV29ya3MvUkwyL3JsMi9tdWx0aXBsZS1kYXRlLXBpY2tlci1hMi9zcmMvbXVsdGlwbGUtZGF0ZS1waWNrZXIubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
